id: 8
user: eq19
span: span11
title: eQuantum
repository: Chetabahana/Chetabahana.github.io
action: eq19/grammar/actions/runs/11803376755
description: 

#debug:
#  dist: false
#  compress: true
#  shortcodes: true

lsi: false
incremental: true
highlighter: rouge

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - vendor
  - LICENSE
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [1, 0]
  pinned: [maps, feed, lexer, parser, syntax, grammar, artifacts, attribute, method, model, trace, track]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
